### PR TITLE
Add solution skeleton

### PR DESCRIPTION
**Pull request by billboga**
Contains main project and related test-project.

### CODE REVIEW

**Comment by kendaleiv** [comment]
The build script is expecting tests to be in a tests folder. See https://github.com/ritterim/ef-test-helpers/blob/master/build/Build.msbuild#L44.

**Comment by billboga** [comment]
That's why the tests will always pass :laughing:

**Comment by billboga** [comment]
I'm going to change this to a WIP and make the change.

**Comment by billboga** [comment]
This has been rebased.

**Comment by billboga** [comment]
After converting singular to plural `test` nomenclature , I have rebased again. This is the last time - unless someone wants to submit a PR to my PR.

**Comment by khalidabuhakmeh** [comment]
Assemblies should be `RimDev.[this].[that]`

**Comment by billboga** [comment]
Shutting it down. Evidently, I cannot operate in a non-vNext environment anymore. I'm going to create a new PR using vNext targeting `4.5.1`.

**Pull request closed without merging**
