### PR TITLE
Add initial project skeleton

### PR DESCRIPTION
**Pull request by billboga**
Has project for mainline code and related tests.
Also update gitignore related to vNext setup.
Ref. https://github.com/github/gitignore/blob/fe783cceeb37ca649a8542ceb9b8711aaa7d3a6e/VisualStudio.gitignore

### CODE REVIEW

**Comment by billboga** [comment]
@jrusbatch: will this setup work with our existing TC build process?

**Comment by jrusbatch** [comment]
Not sure. Let's set it up and find out.

**Comment by billboga** [comment]
Changed framework to `dnx451` since the previous `dotnet` is for `4.6`.

**Comment by billboga** [comment]
Superseded by #6.

**Pull request closed without merging**
